CREATE INDEX CONCURRENTLY IDX_ItemUserIds ON Items (ItemUserId);

CREATE OR REPLACE FUNCTION GetUsersItems(
	ItemUserIds TEXT[],
	CountLimit INT
) RETURNS TABLE (ItemURI Items.ItemURI%TYPE) AS $$
BEGIN
	RETURN QUERY (
		SELECT Items.ItemURI FROM Items WHERE Items.ItemUserId = ANY(ItemUserIds) LIMIT CountLimit
	);
END;
$$ LANGUAGE PLPGSQL
SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION GetUsersItems(
	TEXT[],
	INT
) TO PUBLIC;
