CREATE OR REPLACE FUNCTION ItemsIncRepliesCount(
		ItemURIs TEXT[]
	) RETURNS INTEGER AS $$
BEGIN
	PERFORM * FROM Items WHERE ItemURI = ANY(ItemURIs) ORDER BY ItemCreationTimeStamp FOR UPDATE;
	UPDATE Items SET ItemRepliesCount = ItemRepliesCount + 1 WHERE ItemURI = ANY(ItemURIs);
	RETURN 0;
END;
$$ LANGUAGE PLPGSQL
SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION ItemsIncRepliesCount(
	TEXT[]
) TO PUBLIC;

