CREATE OR REPLACE FUNCTION ItemDelete(
	NewItemURI Items.ItemURI%TYPE
	) RETURNS INTEGER AS $$
DECLARE
	SQL VARCHAR;
	DepthSQL VARCHAR;
BEGIN
	DELETE FROM Markers WHERE ItemURI = NewItemURI;
	DELETE FROM Tags WHERE ItemURI = NewItemURI;
	DELETE FROM ItemExceptions WHERE ItemURI = NewItemURI;
	DELETE FROM Items WHERE ItemURI = NewItemURI;
	RETURN 0;
END;
$$ LANGUAGE PLPGSQL
SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION ItemDelete(
	Items.ItemURI%TYPE
) TO PUBLIC;

